### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by epage** [I60R/page#1]
For now, see [trust](https://github.com/japaric/trust) for how to do this.

Eventually, [crate-ci](https://crate-ci.github.io/) will have simpler instructions.

**Comment by I60R** [comment]
Thank you for suggesting this, and providing those very useful links!  
  
I've done initial setup on [travis](https://github.com/I60R/page/tree/travis) branch.  
There also is [testing release](https://github.com/I60R/page/releases/tag/v13.0.4) that will be deleted after I merge *travis* branch into *master*.  

Can you review it? There are some points I doubt:
1) Enabling  i686 support
2) Disabling freebsd support
3) Is [that](https://github.com/I60R/page/blob/cb5316cc3aa5b3d0755a54e3254e1ea39f2d4307/ci/before_deploy.sh#L20) optimal way to build multiple binaries?
4) Is [travis.yml](https://github.com/I60R/page/blob/cb5316cc3aa5b3d0755a54e3254e1ea39f2d4307/ci/before_deploy.sh#L20) optimal (that's my first CI setup)?

**Comment by epage** [comment]
It all seems reasonable.  I know the recent versions of trust use cross which adds a lot of extra complexity, so I might have missed some things when digging into your setup.

btw is there anything about this project that doesn't work on Windows?  Should support for that be added?

>    Enabling i686 support

What is the concern?  Whether to enable it or not?  I'd probably say its fine to skip in this era

>    Disabling freebsd support

What is the concern?

>    Is that optimal way to build multiple binaries?

Looks like what I'd do.  Again, I plan to make this part trivial in the future

>    Is travis.yml optimal (that's my first CI setup)?

For the bare bones of creating pre-built binaries, it seems fine.  See my crate-ci documentation for how you can offload various parts of reviewing PRs onto your CI.  If nothing else, it sets a clear bar for contributors that they are less likely to take personally when told to go fix it.

**Comment by epage** [comment]
On an unrelated note, thought I'd pass along human-panic which is a recent creation of some CLI-WG members

https://github.com/yoshuawuyts/human-panic

**Comment by I60R** [comment]
>is there anything about this project that doesn't work on Windows? Should support for that be added?

Yes. I use named pipe for communication between `page` and `pty-agent`. That requires `libc` and some `std::os::unix` stuff, which fails to build on Windows.
Replacing that pipe with something more portable and drop `libc` dependency seems to be reasonable.
That will be my next task

>>Disabling freebsd support

>What is the concern?

It seems to be quite unpopular nowadays and there is very little chance that someone will find binaries for it useful

>See my crate-ci documentation for how you can offload various parts of reviewing PRs onto your CI. If nothing else, it sets a clear bar for contributors that they are less likely to take personally when told to go fix it.

Okay, it does make sense, but before I need to decide about my own code style and probably fix some inconsistencies in code

>https://github.com/yoshuawuyts/human-panic

Thank you, I will check it out

**Comment by I60R** [comment]
Windows also don't have `/dev/stdin` and `/dev/stdout` equivalents, which is critical. 
So it's very unlikely that it will be supported

**Comment by I60R** [comment]
I've issued 1.0.0 version, binaries for it might be found on [releases](https://github.com/I60R/page/releases) page
