### ISSUE TITLE
Remove Cargo.lock from .gitignore

### ISSUE THREAD

**Issue by s1341** [I60R/page#10]
Hi,
Would you be willing to remove the Cargo.lock from the .gitignore and commit it?

It would greatly simplify installation on nixos, and would allow me to try to add page to the nixpkgs repo.

Thanks
s1341

**Comment by s1341** [comment]
see https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html for reference (and the comment in your own .gitignore: page is an executable, not a library).

**Comment by I60R** [comment]
Hello,

Sure, yes I'll do that. 

Thank you for making nix package and for this helpful information about Cargo.lock

**Comment by s1341** [comment]
Thanks. Works!

For your reference, here is the nix derivation for v2.3.2:
```
{ stdenv, rustPlatform, fetchFromGitHub }:

rustPlatform.buildRustPackage rec {
  pname = "page";
  version = "v2.3.2";

  src = fetchFromGitHub {
    owner = "I60R";
    repo = pname;
    rev = version;
    sha256 = "1plnli0h9zcmncjn8xv1114lp4pw18hajcpmb1cbmhn43isqn3v5";
  };

  cargoSha256 = "0z1qlz0kpj2vpg3snl51qhmdgs71d2g6bs9mjkb11j545z9b0rrf";

  meta = with stdenv.lib; {
    description = "Use neovim as pager";
    homepage = "https://github.com/I60R/page";
    platforms = platforms.all;
  };
}
```

**Comment by s1341** [comment]
Closing.

**Comment by s1341** [comment]
NixPkgs PR: https://github.com/NixOS/nixpkgs/pull/82949

**Comment by I60R** [comment]
Great!

Would you also like to create PR that adds installation steps for NixOS to README in order to remain in commit history?

**Comment by s1341** [comment]
Will do once the pr is merged.

**Comment by s1341** [comment]
hey @I60R 

We're encountering an issue when running page under the nix-review shell. We get an error like the following:
```
/nix/store/kp60cyq5iig35gzp7l2pr0ilxxa4m919-bash-interactive-4.4-p23/bin/bash: warning: here-document at line 0 delimited by end-of-file (wanted `EOF')
```

Can you look at https://github.com/NixOS/nixpkgs/pull/82949 and see if you can help us figure it out?
