### ISSUE TITLE
Add quit-if-one-screen option

### ISSUE THREAD

**Issue by jlesquembre** [I60R/page#13]
Thanks for writing pager, I find it really useful.
There is only one thing I find annoying. Some commands return a short output, but they use the default `$PAGER` env variable, which I set to `page`. In this cases I'd like to just print the output without calling `page`. In `less` there is a `-F or --quit-if-one-screen` option.  Do you have any plans to add a similar option to `page`? 

In any case, thanks for `page`

**Comment by I60R** [comment]
Hello,

thank you too for good words and for this feature request. It seems to be useful feature, and now I have plans to implement it

**Comment by I60R** [comment]
The functionality is implemented under -O flag in recently published v.3.0.0
