### ISSUE TITLE
Search for pattern and move cursor

### ISSUE THREAD

**Issue by nilehmann** [I60R/page#15]
I'm using `page` for my [scroll back buffer](https://sw.kovidgoyal.net/kitty/#the-scrollback-buffer) in kitty and I would like to set the cursor at the last non-empty line. I tried searching for a particular pattern in my prompt to move the cursor there, but I haven't been able to do it successfully. I believe the problem is that at the time I'm doing the search there's still no text on the screen.
This is what I'm trying:

```vim
au User PageDisconnect call feedkeys("G?╼\<CR>")
```

I also tried redrawing before doing the search but it's still failing.
```vim
au User PageDisconnect redraw | call feedkeys("G?╼\<CR>")
```

Do you have any ideas on how to get around this issue?

Ultimately, I think the problem is the terminal emulator in vim putting empty lines at the end of the buffer.

**Comment by I60R** [comment]
>Do you have any ideas on how to get around this issue?

`map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting page -C -e 'au User PageDisconnect sleep 100m | call feedkeys("G$?\\S\<CR>\<C-l>")'`

This works for me

>Ultimately, I think the problem is the terminal emulator in vim putting empty lines at the end of the buffer.

These lines are sent from kitty e.g. if I have half of the screen empty then that emptiness will be displayed in scrollback preview too and it seems that `less` displays it as well

**Comment by nilehmann** [comment]
> map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting page -C -e 'au User PageDisconnect sleep 100m | call feedkeys("G$?\\S\<CR>\<C-l>")'

Well, that worked pretty well. Thanks!

> These lines are sent from kitty e.g. if I have half of the screen empty then that emptiness will be displayed in scrollback preview too and it seems that less displays it as well

I think kitty sends a couple of lines at the end of the buffer, but the biggest problem for me is when the buffer doesn't fill the entire screen, I think that's related to how the terminal buffer works. For example:

```bash
$ echo -e "1\n2\n3" | page
```
->
```
1
2
3





▮  <- the cursor





```

**Comment by I60R** [comment]
Stripping these trailing lines should fix the issue completely

`map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting bash -c "sd '\s*\z' '' | page -C -e 'au User PageDisconnect sleep 100m | call feedkeys(\"G$?\\\S\<CR>\<C-l>\")'"`

Also, it seems that kitty doesn't support `|` in `map` or does it in unobvious and poorly documented way, so I've must to reuse `bash` for it

**Comment by I60R** [comment]
This could be even simpler:

`map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting bash -c "sd '\s*\z' '' | page -f"`
