### ISSUE TITLE
Remapping <C-\> cause problem in page

### ISSUE THREAD

**Issue by glyh** [I60R/page#22]
As title, I have remapped `<C-\>` to other use, and it turns out to have problem when I use neovim as a pager.

**Comment by I60R** [comment]
Maybe it's due to the fact that page uses :term buffer underneath?

But still `map <C-\> :echo aaa<CR>` works for me in neovim 0.7

Could you check if it persists with page 3.0 version which I've recently published?

**Comment by I60R** [comment]
Or you may need `tmap` so your mapping would work in terminal buffer. Anyway, I think there's nothing wrong on `page` side.
