### ISSUE TITLE
Color for manpages?

### ISSUE THREAD

**Issue by glyh** [I60R/page#25]
Neovim's builtin pager functionality have syntax highlight. But by default page does not seem to have one. So how can I enable it?

**Comment by I60R** [comment]
Works with neovim 7.0:

```zsh
export MANPAGER="page -t man"
```
Also to have even fancier output with `page` version 3.0 (which I've recently published) you can use this function:

```zsh
man() { SECT=${@[-2]}; PROG=${@[-1]}; page man://"$PROG($SECT)" }

# then
man nvim
man 5 nvim
```
