### ISSUE TITLE
Feature Request: cat mode

### ISSUE THREAD

**Issue by MatthiasGrandl** [I60R/page#35]
As a replacement for `bat` and `cat`, it would be nice to have a "cat mode". [nvimpager](https://github.com/lucc/nvimpager) already has this, although it has a few problems, like cat mode not honoring tabstop settings and not working with some plugins like treesitter.

I think a good cat mode would be super usefull, because treesitter syntax highlighting is just so much better than what `bat` has to offer.

**Comment by I60R** [comment]
I think it's doable to allow `page file.type` just echo `file` when it's too short without spawning neovim. But in this case syntax highlighting could be achieved only through `bat`.

That said, I have no idea how to enable treesitter highlighting on echoed text

**Comment by I60R** [comment]
Just drafted a new release where `page -O -- file` will echo `file` if it's too short with syntax highlighting enabled through `bat`

**Comment by I60R** [comment]
Also, did you heard about [syncat](https://github.com/foxfriends/syncat) (uses tree-sitter)

**Comment by I60R** [comment]
Sorry, I see no way to get neovim's highlighting outside of neovim. Perhaps it's possible to somehow leverage treesitter as syncat does, through, the outcome most likely wouldn't be worth the effort.

**Comment by MatthiasGrandl** [comment]
Fair enough, thanks for evaluating the idea!
