### ISSUE TITLE
Cannot parse $RUST_LOG value: ParseLevelError(())

### ISSUE THREAD

**Issue by arcnmx** [I60R/page#36]
Please consider renaming the `RUST_LOG` environment variable to something page specific, such as `PAGE_LOG`. The [parser](https://github.com/I60R/page/blob/8cd17cac46c7b5ff3ddb229d369d4dc403ed5203/src/connection.rs#L61-L65) of the env var is incompatible and cannot coexist with crates that use [env-logger](https://docs.rs/env_logger/latest/env_logger/#enabling-logging). When developing a rust crate, one doesn't expect `git diff` and similar commands to spew out debug output or panic due to this env var being set.

**Comment by I60R** [comment]
Okay, seems to be reasonable to rename it

**Comment by I60R** [comment]
Just drafted a new release with `RUST_LOG` renamed to `PAGE_LOG`

**Comment by I60R** [comment]
Thank you for identifying the issue and reporting it!
