### ISSUE TITLE
Any Possible Way to have Page ignore/bypass greeter plugins like alpha

### ISSUE THREAD

**Issue by dedguy21** [I60R/page#39]
"page" crashes if a greeter plugin (alpha-nvim specific to my issue) is installed. Wondering if there is a workaround for this, beyond just disabling alpha which is used extensively.

**Comment by I60R** [comment]
Hi, the following config for `lazy.nvim` works for me:

```lua
{
    'goolord/alpha-nvim',
    dependencies = {
        'nvim-tree/nvim-web-devicons'
    },
    cond = function()
        for i, v in ipairs(vim.v.argv) do
            if v == '--listen' then return false end
        end
        return true
    end,
    config = function ()
        require'alpha'.setup(require'alpha.themes.startify'.config)
    end
},
```

Since `page` adds `--listen` when spawning neovim we can use it as a condition for enabling `alpha`. Not very elegant but it works. Maybe in the future I'll add some variable for this use case
