### ISSUE TITLE
Page dies with "Error: timeout" on OS X

### ISSUE THREAD

**Issue by s1341** [I60R/page#8]
I tried installing the latest release, and building from source. In both cases, when I pipe anything to page I get the text "Error: Timeout" and neovim exits.

**Comment by s1341** [comment]
Ok. Compiled neovim from source and that seems to fix it.

**Comment by s1341** [comment]
Nope. I was wrong. Compiling neovim from source did NOT fix this issue.

**Comment by I60R** [comment]
Sorry, for delayed response. 

I don't have access to any OS X machine, so I cannot debug it by myself.

Could you redirect to `page` with `RUST_LOG=trace RUST_BACKTRACE=1` and provide output?

**Comment by s1341** [comment]
[INFO][page] options: Options {
    address: None,
    arguments: None,
    config: None,
    command: None,
    command_post: None,
    instance: None,
    instance_append: None,
    instance_close: None,
    name: None,
    filetype: "pager",
    sink_open: false,
    sink_print: false,
    back: false,
    back_restore: false,
    follow: false,
    follow_all: false,
    query_lines: 0,
    page_no_protect: false,
    command_auto: false,
    split_right: 0,
    split_left: 0,
    split_above: 0,
    split_below: 0,
    split_right_cols: None,
    split_left_cols: None,
    split_above_rows: None,
    split_below_rows: None,
    files: []
}
[TRACE][new nvim process] args: --cmd 'set shortmess+=I' --listen /var/folders/h9/m5lk4kcn5s11qg9yw6gllb2r0000gn/T/neovim-page/socket-SZQBTeszf634YTp2lmORjIzynhwyxf1Z

**Comment by I60R** [comment]
Does it work with `TMPDIR=/tmp` when redirecting to `page` ?

**Comment by s1341** [comment]
nope. Same error

**Comment by JeanMertz** [comment]
I've got the same error, also on macOS. Not sure what's happening though, but wanted to corroborate what @s1341 is saying.

**Comment by I60R** [comment]
Here is a new release [v2.0.0](https://github.com/I60R/page/releases/tag/v2.0.0) where all MacOS problems are fixed (at least for me - tested it on MacOS run in VirtualBox).

Thank you for reporting this!

**Comment by s1341** [comment]
Confirmed working. Thanks for the prompt fix!

**Comment by JeanMertz** [comment]
Works for me as well. Awesome, and thank you 👍

**Comment by braham-snyder** [comment]
The latest release gives me the same bug again, `Error: timeout`. [v2.3.5](https://github.com/I60R/page/releases/tag/v2.3.5) still works for me though.
