### ISSUE TITLE
Switch back is ignored when using spawned neovim instance

### ISSUE THREAD

**Issue by JeanMertz** [I60R/page#9]
Using the following command:

```
git --no-pager diff | diff-so-fancy | page
```

I can see some glitches in the output, which seem to originate from [this warning](https://github.com/I60R/page/blob/bd27c6da2ba46782aa993a8b059222e6c44b5e2b/src/context.rs#L142) being printed.

I've solved this for now by launching `page` as:

```
env RUST_LOG=error page
```

* Is there anything I can do on my end to solve this warning?
* Should these warnings be disabled on production binaries?

**Comment by I60R** [comment]
Thank you for reporting, 

it was bug in the previous version of page and it's fixed in 2.2.0.
